### ISSUE TITLE
[Mod Suggestion]: Add a way to add costum Crusher recipes to the Crushers using Config Files.

### ISSUE THREAD

**Issue by Lanse505** [AEnterprise/Buildcraft-Additions#154]
Hello!

I'm making this suggestion seeing as I'm working on a Survival Island Type map and I really would like BCA in the modlist, I planned on using BCA before i realized i could add costum crusher recipes for unsupported things like Exnihilo dusts and such.

So is this something that could perhaps be implemented?

**Comment by AEnterprise** [comment]
@Lanse505 that should be possible to do indeed, it is already possible for other mods to do this but like with eureka i'll add a json thingy to for map makers to also have this option available for them. Any timeframe on when you would want this to be available? could you wait for BCA 2.0 for this (might be a week or more) or would you prefer 1.8.5?

it can still take a week or more for me to add it to 1.8.5 but it'll be sooner then 2.0 then

**Comment by AEnterprise** [comment]
ok, then this'll be inplemented for 2.0 then

glad to hear BCA will be used in such a pack :-)

**Comment by BigXplosion** [comment]
Why don't you just make MineTweaker integration, it's fairly simple to do and, no need for extra config files?

**Comment by AEnterprise** [comment]
that would also be an option, thanks bigXplosion i'll look intro doing that instead

**Comment by Lanse505** [comment]
Nice ^^, Yea i'm making a Sub-Era/Era that build technological and Magical progression overtime, and BCA is going to be put somewhere in Tech stage 1 or 2, as beginning of techonological progression, and later parts of BCA like the kinetic duster and such are parts of early-set BC/PneumaticCraft(Stage3Tech)

**Comment by AEnterprise** [comment]
cool let me know if you need more config options for parts of BC

**Comment by Lanse505** [comment]
We have a teamspeak if you would like to hang out with us and other mod devs ^^

**Comment by AEnterprise** [comment]
@Lanse505 sounds good can you send me the details to join?

**Comment by Lanse505** [comment]
ts.resonant-rise:1337

**Comment by AEnterprise** [comment]
Failed to resolve hostname 'ts.resonant-rise'

**Comment by Lanse505** [comment]
Hmm wait a sec

**Comment by Lanse505** [comment]
ts.resonant-rise.com:1337 >.> totally didnt forget .com

**Comment by AEnterprise** [comment]
@Speiger you didn't read it all, i'm not going to use json filse but minetweaker integration

**Comment by AEnterprise** [comment]
@Lanse505 has been implemented and will be in BCA 2.0

**Comment by Lanse505** [comment]
Nice :)

**Comment by Lanse505** [comment]
Dont forget to include some kind of documentation on how the script should be worded!

**Comment by AEnterprise** [comment]
@Lanse505 where should i put that documentation? also it's very easy, example to add something:
mods.bcadditions.dusters.addDusting(<minecraft:wool:0>, <minecraft:blaze_rod>);

**Comment by Lanse505** [comment]
Okey thanks :), poke StanHebben with it and he can probably make a page of the MT forums about it, or you could poke Jaredlll about it seeing as he's the new Modtweaker Dev :)

**Comment by AEnterprise** [comment]
ok i'll poke them

**Comment by iTitus** [comment]
In Dusters.java you are missing the removeDusting method which actually calls the RemoveDustingAction.
