### ISSUE TITLE
Improve localization

### ISSUE THREAD

**Issue by Adaptivity** [AEnterprise/Buildcraft-Additions#157]
There are some things which can't be translated:
1) ItemCanister.java (lines 59-63) Also, there a should be added %s tag to swap amount of buckets with text.
2) GuiKEB.java (GUI stuff)
3) %s tag should be also added to "tooltip.installed".
4) EventListener.java (Update notifications)
Hope it will be implemented soon because full Russian translation almost done.

**Comment by AEnterprise** [comment]
added this to my todo list

**Comment by AEnterprise** [comment]
feel free to finish the translation and pr on the multiblockRefinery branch

**Comment by Adaptivity** [comment]
You are not fully fixed it. There are still GuiKEB.java not translatable.

**Comment by AEnterprise** [comment]
oeps, my bad, fixing now

**Comment by Adaptivity** [comment]
Also, you are missed event.player.addChatComponentMessage(new ChatComponentText("Changelog: ")); in EventListener.java.

**Comment by Adaptivity** [comment]
Found more: TileKineticEnergyBufferBase.java line 129 and 187

**Comment by AEnterprise** [comment]
also fixed
