### ISSUE TITLE
Quartz Gate doesn't get consume upon Multi-Tool upgrade

### ISSUE THREAD

**Issue by RagaRBM** [AEnterprise/Buildcraft-Additions#158]
Title says it all. Upon upgrading the Multi-Tool, the quartz gate doesn't get consumed while Gold Stick does.

**Comment by AEnterprise** [comment]
probably broke when i updated the recepies in the BC 6.1 -> 6.2 update

**Comment by RagaRBM** [comment]
Oops ... I did a mistake. It is Quartz CHIPSET, not gates. Sorry.

**Comment by Adaptivity** [comment]
The problem applies not only for quartz chipset. It applies for golden chipset and for diamond chipset too.

**Comment by AEnterprise** [comment]
thought as much, must have broken it while updating the api a while back
