### ISSUE TITLE
[Enhancement suggestion] Ability to re-craft Multi-Tool attachments in Assembly Table

### ISSUE THREAD

**Issue by RagaRBM** [AEnterprise/Buildcraft-Additions#159]
This idea come to mind when the Assembly Table automatically picked the Drill Head attachment (while I already have one) to be crafted. The crafting process went so fast, I was not able to be fast enough to cancel out.

**Comment by AEnterprise** [comment]
will do, i'll make it a crafting table thing as otherwise you still would have the same issue and alot of power wasted

**Comment by RagaRBM** [comment]
Thank you.
