### ISSUE TITLE
make kinetic capsules usable as modifier for TiC tools

### ISSUE THREAD

**Issue by AEnterprise** [AEnterprise/Buildcraft-Additions#162]
almost exactly like the TE capacitors

pinging @bonii-xx for more info on how it should be done

**Comment by iTitus** [comment]
EnderIO did it via Reflection. Boni approved in this.

**Comment by BigXplosion** [comment]
well I was looking into TiC code and there wasn't really an easy way to register them, so reflection was also the thing I thought about, as @iTitus said.

**Comment by Speiger** [comment]
Sounds weird but i would go the IC2 way at least for the modifire.
That simply means he check if the mod is loaded and try to load the classes it requires for that.
And implementing Canisters is not that extreme hard.
You simply create a ToolModifire which is based on the class ... let me check... 
ItemModifire... which is more like a recipe class.
That allow you to insert your canisters into the tool.
Then you create a second class that handle your modifires.
That require the class ActiveToolModifire.
And thanks to the IModifyable class you can see every modifire which is inside of an tool.
So you handle the Tinkers construct as a plugin but you require it only inside of your dev invioment..
Only as lib.... (obvious but i wanted to tell)

**Comment by Speiger** [comment]
If you have more questions then ask...

**Comment by AEnterprise** [comment]
i kinda hoped there was an easy api way of doing it :p

**Comment by BigXplosion** [comment]
@Speiger, there is already a modifier for flux tools, so why would we make a new one and have 2 when TE and BCA are installed. just adding BCA items to the list in the ModFlux class will be enough. Also having another dev requirement and core access could cause it to crash and with reflection you can make it so it just doesn't work but the game still loads.

**Comment by Speiger** [comment]
BigExplosion i have mods talking to the core of Other mods and there i nomod requirement at all.
IC2 Classic is the best example.

**Comment by BigXplosion** [comment]
yes I know! but when something in their core changes, it will crash, with reflection you can easily catch the exception and just print out a warning. but the game will still load fine.

**Comment by AEnterprise** [comment]
@BigXplosion you seem to know best how to add it, feel like putting BCA capsules on the list then?

**Comment by BigXplosion** [comment]
sure, give me 20 minutes or so :P

**Comment by bonii-xx** [comment]
Give me a proper PR with IMC and i'll merge it into ticon ;P

**Comment by BigXplosion** [comment]
hmm, I have run in to an error. BC only includes the cofh/api/energy package and not the whole CoFHLib mod, this causes the optional interface to remove the getMaxEnergyStored(ItemStack) in the ToolCore class (in TinkersConstruct). So when an item is added as a ModFlux battery with only BC and BCA installed, it will cause TinkersConstruct to crash...

@bonii-xx I know the optional annotations are there so you do not have to ship api's in the release jars of TinkersConstruct, but I'm not sure what to do now? The only option I see, if you are up for this, is that the optional annotation is removed for IEnergyContainerItem and the that class will be shipped with TinkersConstruct...
