### ISSUE TITLE
Wiki bugs

### ISSUE THREAD

**Issue by Adaptivity** [AEnterprise/Buildcraft-Additions#163]
1) https://buildcraftadditions.wordpress.com/wiki/powerplant/ (screenshots are down)
2) https://buildcraftadditions.wordpress.com/wiki/engineer/ (same as above)
3) https://buildcraftadditions.wordpress.com/wiki/kinetic-multitool/
"And finaly for the forth and final upgrade you’ll need to get a Emerald Stick (only acquirable through trade with the Engineer) and a Golden Chipset:" not a "Golden Chipset" it should be a "Diamond Chipset".

**Comment by AEnterprise** [comment]
sounds like something for @AlexTheGre4t

**Comment by AlexTheGre4t** [comment]
Issues fixed

**Comment by Adaptivity** [comment]
Thanks.
