### ISSUE TITLE
dusters not recognizing TF ores

### ISSUE THREAD

**Issue by AEnterprise** [AEnterprise/Buildcraft-Additions#177]
they don't process TF copper but do process other types of copper but it is registered as copper ore in the oreDict as other machines do process it properly

i suspect this bug isn't limited to the copper witch leads me to beleve it is not recogizing the item when in the duster, maybe something NBT/meta related

pinging @Speiger for more info on possible causes/fixes

**Comment by iTitus** [comment]
Probably because Thermal Foundation registers its ores late?

**Comment by AEnterprise** [comment]
@Udaldor could you provide us with the forge, COFH core and TF version numbers please?

**Comment by iTitus** [comment]
Tested with the newest version of Udaldors Shenanigans on the FTB launcher, duster works with TF ores just fine...

**Comment by AEnterprise** [comment]
if it was broken then it should now at least be fixed by https://github.com/AEnterprise/Buildcraft-Additions/commit/6bb4a948295b773257937955f2ce5306f3f5f94b regarless of when the stuff is registered in the oreDict
