### ISSUE TITLE
Cannot upgrade and craft kinetic multitool in survival

### ISSUE THREAD

**Issue by RagaRBM** [AEnterprise/Buildcraft-Additions#191]
testbuild-4
The kinetic multitool can't be placed inside Integration Table. Same with Iron/Gold/Diamond/Emerald stick. 
Also, I can't craft any buildcraft additions items in the Assembly Table, be it Tool core or sticks.

**Comment by AEnterprise** [comment]
working fine on my end, could you try using the latest jenkins build now that it's building again?
http://ci.tterrag.com/job/Buildcraft-Additions/

**Comment by AEnterprise** [comment]
working as it should
