### ISSUE TITLE
fix and redo dust localization

### ISSUE THREAD

**Issue by AEnterprise** [AEnterprise/Buildcraft-Additions#194]
make a localization using %s for the dust in general and a localization for each of the metals seperatly and have the code assemble it

**Comment by iTitus** [comment]
I have done something similiar for the gas fluids and the buckets (#210). I dont know how hard this will be since some mods use different names for their ores/ingots/dusts (and also different conventions).

**Comment by AEnterprise** [comment]
i'll do it don't worry i have a plan it should be faily simple

**Comment by AEnterprise** [comment]
done in https://github.com/AEnterprise/Buildcraft-Additions/commit/2c8dcbe7d5daf8f095ea2557ad0f09b2bde865ed
