### ISSUE TITLE
Kinetic Buffer causeing sever to crash when attached to Mechanical grinder.

### ISSUE THREAD

**Issue by soulcat1** [AEnterprise/Buildcraft-Additions#199]
Hello I have Built a Kinetic buffer and attached it to a sterling engine.  I placed a Mechanical grinder on top of it.  As Soon as I set the output to up the server crashed.  Here is the crash report:
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 18/01/15 8:45 PM
Description: Ticking block entity

java.lang.ClassCastException: buildcraftAdditions.tileEntities.TileMechanicalDuster cannot be cast to cofh.api.energy.IEnergyHandler
	at buildcraftAdditions.tileEntities.Bases.TileKineticEnergyBufferBase.outputEnergy(TileKineticEnergyBufferBase.java:155)
	at buildcraftAdditions.tileEntities.Bases.TileKineticEnergyBufferBase.func_145845_h(TileKineticEnergyBufferBase.java:144)
	at buildcraftAdditions.tileEntities.TileKineticEnergyBufferTier1.func_145845_h(TileKineticEnergyBufferTier1.java:26)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraftAdditions.tileEntities.Bases.TileKineticEnergyBufferBase.outputEnergy(TileKineticEnergyBufferBase.java:155)
	at buildcraftAdditions.tileEntities.Bases.TileKineticEnergyBufferBase.func_145845_h(TileKineticEnergyBufferBase.java:144)
	at buildcraftAdditions.tileEntities.TileKineticEnergyBufferTier1.func_145845_h(TileKineticEnergyBufferTier1.java:26)

-- Block entity being ticked --
Details:
	Name: TileKineticEnergyBufferTier1 // buildcraftAdditions.tileEntities.TileKineticEnergyBufferTier1
	Block type: ID #212 (tile.blockKEBT1 // buildcraftAdditions.blocks.BlockKineticEnergyBufferTier1)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (42,19,235), Chunk: (at 10,1,11 in 2,14; contains blocks 32,0,224 to 47,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #212 (tile.blockKEBT1 // buildcraftAdditions.blocks.BlockKineticEnergyBufferTier1)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Catsreach
	All players: 1 total; [GCEntityPlayerMP['Soulcat1'/827336, l='Catsreach', x=42.25, y=19.00, z=238.63]]
	Chunk stats: ServerChunkCache: 481 Drop: 0
	Level seed: -760764339
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (11,64,256), Chunk: (at 11,4,0 in 0,16; contains blocks 0,0,256 to 15,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 7976685 game time, 8246262 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 97968 (now: false), thunder time: 119687 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1942187360 bytes (1852 MB) / 2141192192 bytes (2042 MB) up to 2141192192 bytes (2042 MB)
	JVM Flags: 2 total; -Xmx2G -Xms2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 27 mods loaded, 27 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.3.23} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.51} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.51-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.3.1} [BuildCraft] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.3.1} [BC Transport] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.3.1} [BC Silicon] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.3.1} [BC Factory] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	additionalpipes{3.4} [Additional Pipes] (additionalpipes-3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.3.1} [BC Builders] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.3.1} [BC Energy] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Compat{6.3.0} [BuildCraft Compat] (buildcraft-compat-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	eureka{2.2} [Eureka] (Eureka-1.7.10-2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bcadditions{1.8.4} [Buildcraft Additions] (BuildcraftAdditions-1.7.10-1.8.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ImmibisCore{59.0.5} [Immibis Core] (immibis-core-59.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DimensionalAnchors{59.0.2} [Dimensional Anchors] (dimensional-anchor-59.0.2(1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Dynmap{2.0.0-61} [Dynmap] (Dynmap-2.0.0-forge-10.13.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.7} [Galacticraft Core] (GalacticraftCore-1.7-3.0.7.254.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.7} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.7.254.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LunatriusCore{1.1.0.8} [LunatriusCore] (LunatriusCore-1.7.10-1.1.0.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	neiintegration{1.0.0} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Schematica{1.7.0.80} [Schematica] (Schematica-1.7.10-1.7.0.80-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [GCEntityPlayerMP['Soulcat1'/827336, l='Catsreach', x=42.25, y=19.00, z=238.63]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by iTitus** [comment]
We need to update to the newest RF API version...

**Comment by AEnterprise** [comment]
@iTitus there is a newer RF api? didn't knew that

**Comment by iTitus** [comment]
Already fixed in https://github.com/AEnterprise/Buildcraft-Additions/commit/ee5c10a882540efef4d6d984cad55f95ee25d4b4, 2.0 will have the fix

**Comment by AEnterprise** [comment]
issue isn't the RF api indeed but this is quite a severe bug, will backport the fix and probably release a fixed version later today

**Comment by AEnterprise** [comment]
the api or the linked commit where irrelevant but the bug has been fixed now in https://github.com/AEnterprise/Buildcraft-Additions/commit/4f8a449a119f91981b4fe31b8731887557b71cd5
