### ISSUE TITLE
KEB

### ISSUE THREAD

**Issue by Chameleonz** [AEnterprise/Buildcraft-Additions#227]
hi thanks for the mod

you broke the keb`s - the small one wont connect too gold pipes and the buttons on the UI is missing

**Comment by AEnterprise** [comment]
i assume you are using the new testbuild as you are saying buttons are missing? those buttons are no longer in the gui and you now need to make a machine configurator and shift click on a keb to configure input/output settings, also works on 2 of the dusters

as for not connecting to gold pipes i hope you mean gold kinesis pipes, use the tool mentioned above to make sure said side isn't dissabled

**Comment by Chameleonz** [comment]
thank you will try that :)
